#!/bin/bash -e

FLANNEL_VERSION="0.9.1"
HOME_DIR="/home/${SUDO_USER}"

if [[ ${UID} != 0 ]]; then
	echo "Must be root"
	exit 1
fi

usage() {
	echo "kubelocal start|stop|restart"
	exit 0
}

start() {
	echo "Starting local kube node..."
	kubeadm init --pod-network-cidr=10.244.0.0/16


	if [[ -f ${HOME_DIR}/.kube/config ]]; then
		answer='A'
		read -p "${HOME_DIR}/.kube/config already exists. Delete, Move or Abort? D/M/[A]: " answer
		case ${answer} in
			D)
				echo "Overwriting ${HOME_DIR}/.kube/config"
				cp -i /etc/kubernetes/admin.conf ${HOME_DIR}/.kube/config
				chown ${SUDO_UID}:${SUDO_GID} ${HOME_DIR}/.kube/config
				;;
			M)
				echo "Backup copy will be located at ${HOME_DIR}/.kube/config.bak"
				mv ${HOME_DIR}/.kube/config{,.bak}
				cp -i /etc/kubernetes/admin.conf ${HOME_DIR}/.kube/config
				chown ${SUDO_UID}:${SUDO_GID} ${HOME_DIR}/.kube/config
				;;
			A)
				echo "Doing nothing with ${HOME_DIR}/.kube/config."
				echo "Continuing with setup. You will need to configure kubectl yourself once the script completes"
				;;
			*)
				echo "Invalid response. Aborting."
				echo "Not touching ${HOME_DIR}/.kube/config. You will need to configure kubectl yourself once the script completes"
				;;
		esac
	fi

	sleep 5 # Give the API a few seconds before trying to install flannel
	kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v"${FLANNEL_VERSION}"/Documentation/kube-flannel.yml
}

stop() {
	echo "Stopping local kube node..."
	kubeadm reset
}

case $1 in
	start|init)
		start
		;;
	stop|halt)
		stop
		;;
	restart|reset)
		stop
		sleep 3 # Wait a few seconds for things to finish spooling down
		start
		;;
	*)
		usage
		;;
esac

